### PR TITLE
fix post_type_labels Update class-piklist.php

### PR DESCRIPTION
**Pull request by ehababdo**
This is a problem for different English language
modified

'labels' => piklist('post_type_labels', array( 'name' => __('Products', 'piklist') ,'s_name' => __('Product', 'piklist') ) )

### CODE REVIEW

**Comment by sbruner** [comment]
@ehababdo-- Thanks for the pull request!

I tested your code and I'm getting an error when used with the "Piklist Demos": `extract() expects parameter 1 to be array`.

The reason this is happening is because we register "Piklist Demos" with the `piklist(post_type_labels)` function: https://github.com/piklist/piklist/blob/develop/add-ons/piklist-demos/piklist-demos.php#L29

That function is designed to take a simple string and automatically format it for all labels.  This way you don't have to specify all the individual labels when registering a cpt.

Wondering if we should just check for array, and conditionally load the proper code. Thoughts?

**Comment by ehababdo** [comment]
It's true that I have erred in
Thank you for this work

**Comment by sbruner** [comment]
@ehababdo-- Are you able to make your changes work with the `piklist(post_type_labels)` function?

**Comment by JasonTheAdams** [comment]
@ehababdo Checking into the status of this. Are you able to move this PR along?

**Comment by JasonTheAdams** [comment]
@ehababdo Closing this due to inactivity. If you're able to get to it again, please comment and we'll reopen it.

**Pull request closed without merging**
