### PR TITLE
minor bug fix, for custom created folders in the part folder

### PR DESCRIPTION
**Pull request by tidl**
If someone create a custom folder inside the parts folder there will be a warning; "File does not exist .php"
The problem was a small typo, I think.
 I changed '/.php' into '.php' so the files can be accessed as any other file..

Regards,

Tonny

### CODE REVIEW

**Comment by JasonTheAdams** [comment]
HI @tidl! Thanks for the PR! I'll test this out!

**Comment by JasonTheAdams** [comment]
Hey @tidl, I'm having trouble reproducing this bug. I added a `test` directory to `piklist/parts/` in a theme. I'm not seeing any warning when I refresh the admin dash (or anywhere else). I also added a file to the directory. Still nothing.

Can you please provide more information on when this bug shows up?

**Comment by tidl** [comment]
Hi Jason,

I've been very busy lately. 
Sorry for the late response.

My English isn't that great but I'll try to explain.

First of all, it happen in a custom plug-in that is using PikList.
Then I've made a custom post-type, called 'cursist'. 
I added this post-type by using the filter 'piklist_post_types' 

Well, so far all good,
Now it's getting complicated for me...
I decided not to only add some meta-boxes, but also decided to split them up by using workflows.

So I created the workflow first, so each tab will have some nice meta boxes.

/parts/workflows
got some files aka: 
cursist-header.php -> the header
cursist-info.php -> some tab with general information
cursist-orders.php -> some tab with order information

/parts/meta-boxes
got some metabox information files for those tabs
meta-box-cursist-info.php
--> this metabox wil be bound to cursist-info tab
-- > and I insert by using the function "piklist" the custom field form;

**piklist ( 'crm-parts/cursist-info', array ( 'user' => $user_data )  );**

This line above is the one that causes the error: "Warning: File does not exist: .php in wp-content/plugins/piklist/includes/class-piklist.php on line 530"

And my very tiny modification will remove this warning.. that's all.

meta-box-cursist-orders.php
--> this metabox wil be bound to cursist-orders tab
--> same for this one.. etc etc

the custom folder entry
/parts/crm-parts/
here I created some files holding the Piklist fields etc etc
cursist-info.php -> this file will create all kind of piklist fields as I want to us.

The fields are working fine and as mentioned, only the warning is show because of that type.

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

I know it is a bit of scope for the most users, and maybe a weird approach.
But the result is a clear and neat UI for the ones that are going the use it.
Also I can have full control this way for delegation of rights.

Kind regards,

Tonny Keuken

**Comment by JasonTheAdams** [comment]
Hi @tidl!

Thanks for the explanation! I've used the piklist render function very similarly. I've seen this issue before, but I don't think this is the right place to fix it. All that would do is prevent it from throwing an error when a blank `.php` file is selected, but I'd rather figure out why that is even happening to begin with, upstream.

**Pull request closed without merging**
