### PR TITLE
Fix inverted parameters

### PR DESCRIPTION
**Pull request by kadimi**

### CODE REVIEW

**Comment by sbruner** [comment]
Thank you!

**Comment by kadimi** [comment]
You're most welcome. Thanks for your great work.

I want to write a response [here](https://piklist.com/support/topic/title-translation/) which I believe can help many. Do you mind re-opening that topic?

**Comment by sbruner** [comment]
I just opened.

**Comment by kadimi** [comment]
Thanks!

**Comment by sbruner** [comment]
This is included in Piklist v1.0.5. Thank you!

**Comment by kadimi** [comment]
Thanks!

**Pull request merged**
