### PR TITLE
fix invalid index in array compare

### PR DESCRIPTION
**Pull request by donnamcmaster**
- was seeing error about invalid index "order"; this happened when one of the two array elements being compared didn't have an ['args']['order'] element
- the code was returning zero only if both were not set
- changed && to || so that if either is not set, return value is 0

### CODE REVIEW

**Comment by donnamcmaster** [comment]
this is my first pull request so please forgive me if I goofed and let me know what I should have done differently!

**Comment by JasonTheAdams** [comment]
@donnamcmaster Hi! Thanks for contributing!

Just so I understand, where you were seeing this error happen? I understand the context in the code, but were you seeing this on a screen? Or if some metaboxes had order and others didn't?

**Comment by donnamcmaster** [comment]
Hi @JasonTheAdams  
Yes, I got an error message: 
`Notice:  Undefined index: order in /Users/donna/Sites/coloma/wp-content/plugins/piklist/includes/class-piklist.php on line 2310`
And when I dug into it, I found that metaboxes generated by the SEO Framework plugin didn't have an 'order' field under ['args']. https://wordpress.org/plugins/autodescription/

**Comment by JasonTheAdams** [comment]
Got it. So I'm looking at the following lines and feeling like this should be working differently. Take a look at this:
```php
$a['args']['order'] = is_numeric($a['args']['order']) ? $a['args']['order'] : 0;
```
That's checking to see if there is a numeric value, and then otherwise sets it to a default of 0. The affect of this would be that ordered metaboxes would likely appear _after_ metaboxes without a specified order (as it's ascending). Perhaps it should be the opposite, where ordered metaboxes go first. What this patch would do is make so if either order is undefined then they're left as-is. And perhaps that would be best. That's ok, I just want to make the decision intentional rather than just fixing the issue. Have any thoughts on what you feel would be optimal behavior?

@kevinpmiller Would you please weigh in on this?

**Comment by sbruner** [comment]
@JasonTheAdams @kevinpmiller instead of 0, should we set it to 10?  That's the default priority for WordPress.

**Comment by donnamcmaster** [comment]
@JasonTheAdams @sbruner your recommendations make good sense to me

**Comment by JasonTheAdams** [comment]
@sbruner I'm not sure where you're getting that from? Metaboxes are added via add_meta_box, which has a context and priority, but the priority is sectional, not numeric. It was my understanding that this is why Piklist even added that functionality, as by default metaboxes are simply displayed in the order they're added (within context and priority). I'm happy to be proven wrong on this, however.

In any case, perhaps a default priority of 10 is a good idea.

**Comment by sbruner** [comment]
@JasonTheAdams you are correct. However, Piklist extends this in an awesome way, by allowing the user to sort metaboxes numerically. 

WordPress defaults priorities to 10, so you can trigger actions before and after default functions.  Setting our metaboxes to 10, would allow users to place metaboxes before and after those not created with Piklist.

**Comment by JasonTheAdams** [comment]
I'm going to go ahead and merge this pull request. We've had a lot of discussion, internally, about whether we should change this code, but we've decided not to for now. The follow sums up the options we identified, wherein the first option is the way this PR works now.

----

## 1) Boxes without a specified order are left alone
In other words, if either is unset then return 0

### Pros:
- Things work pretty much the way they are now, so there's no interruption.
### Cons:
- In order to change the order of a non-piklist box it must be extended and the order set.


## 2) Boxes without a specified order get a default of 10
### Pros:
- It's easy to move Piklist boxes above or below these boxes
### Cons:
- Since they're all 10 it's not easy to put a box inbetween them. Boxes would have to be extended to pull this off reliably.
- This will very likely mess with (I know it will affect some of mine) existing layouts the next time someone updates.


## 3) Boxes without a specified order go to the bottom
### Pros:
- Pretty simple default and order gets prevelance, which is likely the intention.
- Existing layouts are likely not affected in a negative way.
### Cons:
- In order to put a box below one of the affect boxes, they would have to be extended.

----

## Conclusion
The first option is the safest, and all three really require extending boxes to achieve a truly customized layout, so I'm inclined to go with that.

I don't like the adverse (and potentially jarring) affect the second option has, but I do appreciate it's long-term affect (once the initial damage happens).

The third option is a bit of a compromise, where order gets more prevelance and the immediate change is likely favorable, but in terms of control it doesn't really help.

**Pull request merged**
