### PR TITLE
Add composer support

### PR DESCRIPTION
**Pull request by lucalbert**
Add composer support.

After add composer.json to project, you simply must registered the package on [packagist](https://packagist.org/).

### CODE REVIEW

**Comment by JasonTheAdams** [comment]
Hey @lucalbert! Thanks for the PR!

Just to be clear, is this intended to make it possible for the plugin to be installed within `wp-content/plugins` via composer, or for loading Piklist as a dependency for other plugins?

If the latter, we'd have to do more work to make it possible (see #11).

**Comment by lucalbert** [comment]
Hi @JasonTheAdams,

At first, it is essentially to install the plugin in `wp-content/plugins`.

Today the plugin is available via composer thanks to [wpackagist](https://wpackagist.org/search?q=piklist&type=any&search=). 

But wpackagist synchronizes the SVN of WordPress and now that Piklist is on Github the new versions are no longer available :-(

**Comment by JasonTheAdams** [comment]
Ah, I see. To be clear, public releases will still go in the WordPress plugin repository. That's not changing. The only thing that's exclusive to github are beta versions and development.

**Comment by lucalbert** [comment]
Okay.

So this is a bit of another topic but the project has not been updated on the WordPress SVN for 6 months. However, the last version (0.9.9.12) is bugged ([see this post](https://piklist.com/support/topic/post-status-remains-draft-in-submitbox/#post-7942)): a version 0.9.9.13 would have been available on Github a few months ago but has disappeared ... and has never been delivered on the WordPress repository .

It is obvious that to have a good visibility, the project must continue to live on the WordPress repository.
But I think it would be interesting that both channels (dev/beta and stable) are available via composer. Especially since they will have 2 different "composer" names:

* Github/Packagist = `piklist/piklist`
* WordPress/Wpackagist = `wpackagist-plugin/piklist`

Free to everyone to use the channel that suits him not?

**Pull request merged**
