### PR TITLE
Added a filter to allow setting custom field aliases

### PR DESCRIPTION
**Pull request by manutiedra**
Right now there is no way to add custom field aliases, so I added a filter to do that, in a similar way to what you do with field_list_types

### CODE REVIEW

**Comment by sbruner** [comment]
Please provide an example of usage

**Comment by manutiedra** [comment]
In https://github.com/manutiedra/piklist-autocomplete, the file parts/fields/autocomplete.php is just an exact copy of the standard piklist/parts/fields/select.php

Adding an alias from autocomplete to select I can remove that file.

**Comment by sbruner** [comment]
Can you please check "Allow edits from maintainers": https://help.github.com/assets/images/help/pull_requests/allow-maintainers-to-make-edits-sidebar-checkbox.png

I'd like to modify your PR a little:
https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by manutiedra** [comment]
Hi @sbruner ,

this pull request and the other one that I sent today already have "Allow edits from maintainers" checked. 

Let me know if you need something else.

BR,
Manu

**Comment by sbruner** [comment]
I adjusted your PR here: https://github.com/piklist/piklist/commit/154a5181f26f04b893fe7c116520e02f826f845b

Sorry, I didn't edit this PR directly

**Comment by manutiedra** [comment]
thank you!

**Comment by manutiedra** [comment]
Hi @sbruner,

the way you left the code makes me impossible to add entries to $field_list_types['multiple_value'], Recall that $field_list_types is an array of arrays.

Also, I think you made a mistake because you call apply_filters('piklist_field_alias' twice. I think the second one should be removed.

**Pull request merged**
