### PR TITLE
Couldn't remove custom attachments by clicking on the preview

### PR DESCRIPTION
**Pull request by alasdaircr**
Just a typo fix on `id` => `index`

Thanks for fixing the default public status issue :-)

### CODE REVIEW

**Comment by sbruner** [comment]
@alasdaircr -- please provide steps to reproduce issue so we can test.

**Comment by sbruner** [comment]
@alasdaircr -- I totally get that. But I'd still like to see the issue and verify it's working properly.  Please give a little more detail about what this means: Couldn't remove custom attachments by clicking on the preview 

Thanks

**Comment by alasdaircr** [comment]
Ok –  but bear with me as I might use the incorrect terminology.

Add a meta-field of type `file` to a wordpress post. Save the post with a field uploaded.

Click the remove (-) button on the preview icon. Look in the console for `piklist.js?ver=0.11.2:1976 Uncaught ReferenceError: id is not defined
    at HTMLButtonElement.<anonymous> (piklist.js?ver=0.11.2:1976)`

**Comment by alasdaircr** [comment]
Ok –  but bear with me as I might use the incorrect terminology.

Add a meta-field of type `file` to a wordpress post. Save the post with a file attached to the field.

Click the `remove` (-) button on the preview icon. Look in the console for `piklist.js?ver=0.11.2:1976 Uncaught ReferenceError: id is not defined
    at HTMLButtonElement.<anonymous> (piklist.js?ver=0.11.2:1976)`

Apply the patch and reload the JS.

**Comment by sbruner** [comment]
@alasdaircr -- tested and works great.

Fixes: https://github.com/piklist/piklist/issues/94

**Comment by sbruner** [comment]
@alasdaircr thanks so much!

**Pull request merged**
