### PR TITLE
Update relate query support to WordPress 4.7 standards

### PR DESCRIPTION
**Pull request by JasonTheAdams**
The way additional query parameters are supported were changed when the REST API was merged into core in 4.7. This begins to fix that issue and so far allows for `post_has` and `post_belongs` to be used in the query.

Important Note: The `relate_query` parameter was not added on purpose. It's easy to sanitize `post_has` and `post_belongs`, but `relate_query` is a complex collection. Furthermore, it's worth considering that if something more complex is needed, the developer at that time should probably make their own query var that builds the `relate_query` itself. This reduces the complexity of the query and improves security.

I'm very interested in anyones thoughts that would like to chime in.

### CODE REVIEW

**Comment by beatelite** [comment]
I support this and feel that the post_has and post_belongs filters will suffice for now. It would be great to have some docs or some starter code on how to build a more complex query but that's for another time.  Thanks for this Jason! When it's done, I'll test it out for you.

**Comment by JasonTheAdams** [comment]
Awesome, thanks for the input @beatelite! Not sure what you mean by "when it's done", though. The branch should be working for post-type requests.

**Comment by beatelite** [comment]
Ok, I'll test after the holiday weekend then.

**Comment by JasonTheAdams** [comment]
@beatelite Did you happen to test this out?

**Comment by beatelite** [comment]
Not yet, got tied up on some other bugs in our app. Will test by next week for sure.

**Comment by kevinpmiller** [comment]
@JasonTheAdams Has this been tested? Thoughts?

**Comment by JasonTheAdams** [comment]
@kevinpmiller Just tested this. I also added another commit which enables the piklist demo post type with the rest api so users can play around with the rest api and piklist. The `post_has` and `post_belongs` query parameters are working great.

**Pull request merged**
